language: node_js
node_js:
  - 8

cache:
  directories:
    - "node_modules"

env:
  - WEB_INDEX=.vuepress/dist/index.html

install:
  - yarn
  - yarn upgrade

script:
  - yarn build
  - test -f $WEB_INDEX -a -s $WEB_INDEX

deploy:
  email: a2263266@gmail.com
  github-token: $GITHUB_TOKEN
  local-dir: .vuepress/dist
  name: Jun-Min Wang
  provider: pages
  skip-cleanup: true
  target-branch: master
  on:
    branch: vuepress

  branches:
    only:
      - vuepress

  notifications:
    email:
      on_failure: always
